---
title: "MultiNichenet"
output:
  html_document: default
  pdf_document: default
date: "2024-04-12"
---

```{r setup, include=FALSE}
# https://github.com/saeyslab/multinichenetr/blob/main/vignettes/3-multinichenet_interpretation_MSA_final.Rmd
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.path = "/Users/fischer/Documents/science/projects/ovaries/results/segmentation/panels/ccc/")
```

## Setup

```{r installation, echo=FALSE}
packages <- c(
    'anndata', "Seurat","tidyverse","ggraph",
    'RColorBrewer','viridis',
    'hdf5r', 'reticulate')

loadpak <- function(pkg){
  new.pkg <- pkg[!(pkg %in% installed.packages()[, "Package"])]
  if (length(new.pkg))
    install.packages(new.pkg, dependencies = TRUE)
    suppressPackageStartupMessages(sapply(pkg, require, character.only = TRUE))
}
#library(devtools)
#if (!("DIALOGUE" %in% installed.packages()[, "Package"]))
#    devtools::install_github(repo = "https://github.com/livnatje/DIALOGUE")
#if (!("SCP" %in% installed.packages()[, "Package"]))
#    devtools::install_github(repo = "https://github.com/zhanghao-njmu/SCP")
#if (!("SeuratDisk" %in% installed.packages()[, "Package"]))
#    if (!requireNamespace("remotes", quietly = TRUE)) {
#      install.packages("remotes")
#    }
#    remotes::install_github("mojaveazure/seurat-disk")

#BiocManager::install("SingleR")
#BiocManager::install("scRNAseq")
#BiocManager::install("SingleCellExperiment")

#devtools::install_github("saeyslab/nichenetr")
#devtools::install_github("saeyslab/multinichenetr")
```

```{r libraries}
library(hdf5r)
library(Seurat)
library(SeuratDisk)

library(SingleCellExperiment)
library(dplyr)
library(ggplot2)
library(nichenetr)
library(multinichenetr)

organism = "mouse"
if(organism == "human"){
  lr_network_all = readRDS(url("https://zenodo.org/record/10229222/files/lr_network_human_allInfo_30112033.rds")) %>% 
    mutate(
      ligand = convert_alias_to_symbols(ligand, organism = organism), 
      receptor = convert_alias_to_symbols(receptor, organism = organism))
  
  lr_network_all = lr_network_all  %>% 
    mutate(ligand = make.names(ligand), receptor = make.names(receptor)) 
  
  lr_network = lr_network_all %>% 
    distinct(ligand, receptor)
  
  ligand_target_matrix = readRDS(url("https://zenodo.org/record/7074291/files/ligand_target_matrix_nsga2r_final.rds"))

  colnames(ligand_target_matrix) = colnames(ligand_target_matrix) %>% 
    convert_alias_to_symbols(organism = organism) %>% make.names()
  rownames(ligand_target_matrix) = rownames(ligand_target_matrix) %>% 
    convert_alias_to_symbols(organism = organism) %>% make.names()
  
  lr_network = lr_network %>% filter(ligand %in% colnames(ligand_target_matrix))
  ligand_target_matrix = ligand_target_matrix[, lr_network$ligand %>% unique()]
} else if(organism == "mouse"){
  #lr_network_all = readRDS(url("https://zenodo.org/record/10229222/files/lr_network_mouse_allInfo_30112033.rds")) %>% 
  #  mutate(
  #    ligand = convert_alias_to_symbols(ligand, organism = organism), 
  #    receptor = convert_alias_to_symbols(receptor, organism = organism))
  lr_network_all = readRDS(paste0("/Users/fischer/Documents/science/projects/ovaries/nichenet_input/", 
                              "lr_network_mouse_allInfo_30112033.rds")) %>% 
    mutate(
      ligand = convert_alias_to_symbols(ligand, organism = organism), 
      receptor = convert_alias_to_symbols(receptor, organism = organism))
  
  lr_network_all = lr_network_all  %>% 
    mutate(ligand = make.names(ligand), receptor = make.names(receptor))
  
  lr_network = lr_network_all %>% 
    distinct(ligand, receptor)

  #ligand_target_matrix = readRDS(url("https://zenodo.org/record/7074291/files/ligand_target_matrix_nsga2r_final_mouse.rds"))
  ligand_target_matrix = readRDS(paste0("/Users/fischer/Documents/science/projects/ovaries/nichenet_input/",
                                        "ligand_target_matrix_nsga2r_final_mouse.rds"))
  colnames(ligand_target_matrix) = colnames(ligand_target_matrix) %>% 
    convert_alias_to_symbols(organism = organism) %>% make.names()
  rownames(ligand_target_matrix) = rownames(ligand_target_matrix) %>% 
    convert_alias_to_symbols(organism = organism) %>% make.names()
  
  lr_network = lr_network %>% filter(ligand %in% colnames(ligand_target_matrix))
  ligand_target_matrix = ligand_target_matrix[, lr_network$ligand %>% unique()]
}
```

```{r read, echo=FALSE}

fn <- "/Users/fischer/Documents/science/projects/ovaries/h5ads/ccc/spots_240924_segments_ageYoung_stageAll_segmentFollicle_withOocyte.h5ad"
read_h5_follicle <- function(file) {
    s1 <- H5File$new(file, mode = 'r')
    s1m <- Matrix::sparseMatrix(
      i = s1[['raw/X/indices']][],
      p = s1[['raw/X/indptr']][],
      x = s1[['raw/X/data']][],
      dimnames = list(
          s1[['raw/var/_index']][],
          s1[['obs/_index']][]
      ),
      dims = c(
        length(s1[['raw/var/_index']][]),
        length(s1[['obs/_index']][])
      ),
      index1 = FALSE
    )
    obj <- CreateSeuratObject(s1m, min.features=0, min.cells=0, assay = "RNA")
    obj@meta.data$puck <- s1[["obs/puck/categories"]][][s1[["obs/puck/codes"]][] + 1]
    obj@meta.data$cell_type <- s1[["obs/segment_layer/categories"]][][s1[["obs/segment_layer/codes"]][] + 1]
    obj@meta.data$age <- s1[["obs/Age/categories"]][][s1[["obs/Age/codes"]][] + 1]
    obj@meta.data$stage <- s1[["obs/stage/categories"]][][s1[["obs/stage/codes"]][] + 1]
    obj@meta.data$mouse <- s1[["obs/mouse/categories"]][][s1[["obs/mouse/codes"]][] + 1]
    obj@meta.data$batch <- s1[["obs/batch/categories"]][][s1[["obs/batch/codes"]][] + 1]
    obj@meta.data$segment_id <- s1[["obs/segment_id/categories"]][][s1[["obs/segment_id/codes"]][] + 1]
    obj@meta.data$segment_label <- s1[["obs/segment_label/categories"]][][s1[["obs/segment_label/codes"]][] + 1]
    obj@meta.data$segment_label_coarse <- s1[["obs/segment_label_coarse/categories"]][][s1[["obs/segment_label_coarse/codes"]][] + 1]
    obj@meta.data$segment_type <- s1[["obs/segment_type/categories"]][][s1[["obs/segment_type/codes"]][] + 1]
    # Watch out, sometimes a categorical has -1 entries: for classes not matched to any group, ie none in python?
    return(obj)
}
srobj <- read_h5_follicle(fn)
```

```{r sce}
sce <- Seurat::as.SingleCellExperiment(srobj, assay = "RNA")
#sce@assays@data$logcounts@x <- log(sce@assays@data$counts + 1)
sce = alias_to_symbol_SCE(sce, "mouse") %>% makenames_SCE()
sce@colData$cell_type <- make.names(sce@colData$cell_type)
# Rename grouping so that plots below appear in correct ordering:
map = setNames(
  c("state1_preantral", "state2_antral", "state3_atretic"), 
  c("preantral", "antral", "atretic"))
sce@colData$segment_label_coarse <- factor(
  unname(map[unlist(sce@colData$segment_label_coarse)]), 
  levels = c("state1_preantral", "state2_antral", "state3_atretic"))
sce@colData
```

## Prepare

```{r prepare}
sample_id = "segment_id"
group_id = "segment_label_coarse"
celltype_id = "cell_type"
covariates = NA 
batches = NA

senders_oi = c("oocyte", "granulosa", "theca", "immune")
receivers_oi = c("oocyte", "granulosa", "theca", "immune")

sce = sce[, SummarizedExperiment::colData(sce)[,celltype_id] %in% c(senders_oi, receivers_oi)]

min_cells = 5

abundance_info <- get_abundance_info(
  sce = sce, 
  sample_id = sample_id, 
  group_id = group_id, 
  celltype_id = celltype_id, 
  min_cells = min_cells, 
  senders_oi = senders_oi, 
  receivers_oi = receivers_oi, 
  batches = batches)

abundance_info$abund_plot_sample
```

```{r abund_plot_group}
abundance_info$abund_plot_group
```

```{r abund_barplot}
abundance_info$abund_barplot
```
```{r expression}
fraction_cutoff = 0.05
min_sample_prop = 0.50

frq_list <- get_frac_exprs(
  sce = sce, 
  sample_id = sample_id, celltype_id =  celltype_id, group_id = group_id, 
  batches = batches, 
  min_cells = min_cells, 
  fraction_cutoff = fraction_cutoff, min_sample_prop = min_sample_prop)
genes_oi = frq_list$expressed_df %>% 
  filter(expressed == TRUE) %>% pull(gene) %>% unique() 
sce = sce[genes_oi, ]

abundance_expression_info <- process_abundance_expression_info(
  sce = sce, 
  sample_id = sample_id, group_id = group_id, celltype_id = celltype_id, 
  min_cells = min_cells, 
  senders_oi = senders_oi, receivers_oi = receivers_oi, 
  lr_network = lr_network, 
  batches = batches, 
  frq_list = frq_list, 
  abundance_info = abundance_info)
```

## Fit

```{r fit}
contrasts_oi = c(paste0(
  "'state1_preantral-(state2_antral+state3_atretic)/2',",
  "'state2_antral-(state1_preantral+state3_atretic)/2',",
  "'state3_atretic-(state2_antral+state1_preantral)/2'"
))
contrast_tbl = tibble(
  contrast = c(
    "state1_preantral-(state2_antral+state3_atretic)/2",
    "state2_antral-(state1_preantral+state3_atretic)/2",
    "state3_atretic-(state2_antral+state1_preantral)/2"
    ), 
  group = c("state1_preantral", "state2_antral", "state3_atretic"))
DE_info = get_DE_info(
  sce = sce, 
  sample_id = sample_id, 
  group_id = group_id, 
  celltype_id = celltype_id,
  batches = batches,
  covariates = covariates,
  contrasts_oi = contrasts_oi, 
  min_cells = min_cells, 
  expressed_df = frq_list$expressed_df)
DE_info$celltype_de$de_output_tidy %>% arrange(p_adj) %>% head()
```

```{r de}
celltype_de = DE_info$celltype_de$de_output_tidy
sender_receiver_de = multinichenetr::combine_sender_receiver_de(
  sender_de = celltype_de,
  receiver_de = celltype_de,
  senders_oi = senders_oi,
  receivers_oi = receivers_oi,
  lr_network = lr_network
)
sender_receiver_de %>% head(20)
```

## Ligand activities

```{r gene_set_assessment}
# Defaul thresholds from tutorial:
logFC_threshold = 0.5
p_val_threshold = 0.05
p_val_adj = FALSE

geneset_assessment = contrast_tbl$contrast %>% 
  lapply(
    process_geneset_data, 
    celltype_de, logFC_threshold, p_val_adj, p_val_threshold
  ) %>% 
  bind_rows() 
geneset_assessment
```

```{r lig}
top_n_target = 250

verbose = TRUE
cores_system = 1 # 8
n.cores = min(cores_system, sender_receiver_de$receiver %>% unique() %>% length()) # use one core per receiver cell type

ligand_activities_targets_DEgenes = get_ligand_activities_targets_DEgenes(
  receiver_de = celltype_de,
  receivers_oi = receivers_oi,
  ligand_target_matrix = ligand_target_matrix,
  logFC_threshold = logFC_threshold,
  p_val_threshold = p_val_threshold,
  p_val_adj = p_val_adj,
  top_n_target = top_n_target,
  verbose = verbose, 
  n.cores = n.cores
)

ligand_activities_targets_DEgenes$de_genes_df %>% head(20)
```

```{r lig2}
ligand_activities_targets_DEgenes$ligand_activities %>% head(20)
```

```{r prioritize}
fraction_cutoff = 0.05
ligand_activity_down = FALSE

sender_receiver_tbl = sender_receiver_de %>% dplyr::distinct(sender, receiver)

metadata_combined = SummarizedExperiment::colData(sce) %>% tibble::as_tibble()

if(!is.na(batches)){
  grouping_tbl = metadata_combined[,c(sample_id, group_id, batches)] %>% tibble::as_tibble() %>% dplyr::distinct()
  colnames(grouping_tbl) = c("sample","group",batches)
} else {
  grouping_tbl = metadata_combined[,c(sample_id, group_id)] %>% tibble::as_tibble() %>% dplyr::distinct()
  colnames(grouping_tbl) = c("sample","group")
}

prioritization_tables = multinichenetr::generate_prioritization_tables(
  sender_receiver_info = abundance_expression_info$sender_receiver_info,
  sender_receiver_de = sender_receiver_de,
  ligand_activities_targets_DEgenes = ligand_activities_targets_DEgenes,
  contrast_tbl = contrast_tbl,
  sender_receiver_tbl = sender_receiver_tbl,
  grouping_tbl = grouping_tbl,
  scenario = "regular", # all prioritization criteria will be weighted equally
  fraction_cutoff = fraction_cutoff, 
  abundance_data_receiver = abundance_expression_info$abundance_data_receiver,
  abundance_data_sender = abundance_expression_info$abundance_data_sender,
  ligand_activity_down = ligand_activity_down
)

prioritization_tables$group_prioritization_tbl %>% head(20)
```

```{r save}
lr_target_prior_cor = lr_target_prior_cor_inference(
  prioritization_tables$group_prioritization_tbl$receiver %>% unique(),
  abundance_expression_info, 
  celltype_de, 
  grouping_tbl, 
  prioritization_tables, 
  ligand_target_matrix, 
  logFC_threshold = logFC_threshold, 
  p_val_threshold = p_val_threshold,
  p_val_adj = p_val_adj)

path = "/Users/fischer/Documents/science/projects/ovaries/results/nichenet/ageYoung_stageAll_segmentFollicle_withOocyte_byCluster/"

multinichenet_output = list(
    celltype_info = abundance_expression_info$celltype_info,
    celltype_de = celltype_de,
    sender_receiver_info = abundance_expression_info$sender_receiver_info,
    sender_receiver_de =  sender_receiver_de,
    ligand_activities_targets_DEgenes = ligand_activities_targets_DEgenes,
    prioritization_tables = prioritization_tables,
    grouping_tbl = grouping_tbl,
    lr_target_prior_cor = lr_target_prior_cor
  ) 
multinichenet_output = make_lite_output(multinichenet_output)
```

```{r save-table}
write.table(multinichenet_output$prioritization_tables$sample_prioritization_tbl, 
            file = paste0(path, "sample_prioritization_tbl.csv"), sep = ",")
```

## Visualize

```{r circos}
# Default:
#prioritized_tbl_oi_all = get_top_n_lr_pairs(
#  multinichenet_output$prioritization_tables, 
#  top_n = 50, 
#  rank_per_group = FALSE)
# Deviating from tutorial here to rank per group to have balanced circos plots:
prioritized_tbl_oi_all = get_top_n_lr_pairs(
  multinichenet_output$prioritization_tables, 
  top_n = 20, 
  rank_per_group = TRUE)

prioritized_tbl_oi = 
  multinichenet_output$prioritization_tables$group_prioritization_tbl %>%
  filter(id %in% prioritized_tbl_oi_all$id) %>%
  distinct(id, sender, receiver, ligand, receptor, group) %>% 
  left_join(prioritized_tbl_oi_all)
prioritized_tbl_oi$prioritization_score[is.na(prioritized_tbl_oi$prioritization_score)] = 0

senders_receivers = union(prioritized_tbl_oi$sender %>% unique(), prioritized_tbl_oi$receiver %>% unique()) %>% sort()

colors_sender = RColorBrewer::brewer.pal(n = length(senders_receivers), name = 'Spectral') %>% magrittr::set_names(senders_receivers)
colors_receiver = RColorBrewer::brewer.pal(n = length(senders_receivers), name = 'Spectral') %>% magrittr::set_names(senders_receivers)
circos_list = make_circos_group_comparison(prioritized_tbl_oi, colors_sender, colors_receiver)

pdf(paste0(path, "circos_preantral.pdf"), width = 10, height = 10)
circos_list$state1_preantral
dev.off()

pdf(paste0(path, "circos_antral.pdf"), width = 10, height = 10)
circos_list$state2_antral
dev.off()

pdf(paste0(path, "circos_atretic.pdf"), width = 10, height = 10)
circos_list$state3_atretic
dev.off()

pdf(paste0(path, "circos_legend.pdf"), width = 10, height = 10)
circos_list$legend
dev.off()

circos_list
```

## Intercellular regulatory network inference

```{r network}
# Recomputing this here so that network function works:
prioritized_tbl_oi_all = get_top_n_lr_pairs(
  multinichenet_output$prioritization_tables, 
  top_n = 20, 
  rank_per_group = TRUE)

lr_target_prior_cor_filtered = 
  multinichenet_output$prioritization_tables$group_prioritization_tbl$group %>% unique() %>% 
  lapply(function(group_oi){
    lr_target_prior_cor_filtered = multinichenet_output$lr_target_prior_cor %>%
      inner_join(
        multinichenet_output$ligand_activities_targets_DEgenes$ligand_activities %>%
          distinct(ligand, target, direction_regulation, contrast)
        ) %>% 
      inner_join(contrast_tbl) %>% filter(group == group_oi)
    
    lr_target_prior_cor_filtered_up = lr_target_prior_cor_filtered %>% 
      filter(direction_regulation == "up") %>% 
      filter( (rank_of_target < top_n_target) & (pearson > 0.33))
    
    lr_target_prior_cor_filtered_down = lr_target_prior_cor_filtered %>% 
      filter(direction_regulation == "down") %>% 
      filter( (rank_of_target < top_n_target) & (pearson < -0.33))
    lr_target_prior_cor_filtered = bind_rows(
      lr_target_prior_cor_filtered_up, 
      lr_target_prior_cor_filtered_down
      )
}) %>% bind_rows()

lr_target_df = lr_target_prior_cor_filtered %>% 
  distinct(group, sender, receiver, ligand, receptor, id, target, direction_regulation) 

network = infer_intercellular_regulatory_network(lr_target_df, prioritized_tbl_oi_all)

prioritized_tbl_oi_network = prioritized_tbl_oi_all %>% inner_join(
  network$prioritized_lr_interactions)

network_graph = visualize_network(network, colors_sender)

pdf(paste0(path, "network.pdf"), width = 15, height = 10)
network_graph$plot
dev.off()

network_graph$plot
```

## Detailed plots

```{r dotplot_state1_preantral}
group_oi = "state1_preantral"
prioritized_tbl_oi = prioritized_tbl_oi_network %>% filter(group == group_oi)
plot_oi = make_sample_lr_prod_activity_plots_Omnipath(
  multinichenet_output$prioritization_tables, 
  prioritized_tbl_oi %>% inner_join(lr_network_all))

pdf(paste0(path, "dotplot_preantral.pdf"), width = 25, height = 15)
plot_oi
dev.off()

plot_oi
```

```{r dotplot_state2_antral}
group_oi = "state2_antral"

prioritized_tbl_oi = prioritized_tbl_oi_network %>% filter(group == group_oi)
plot_oi = make_sample_lr_prod_activity_plots_Omnipath(
  multinichenet_output$prioritization_tables, 
  prioritized_tbl_oi %>% inner_join(lr_network_all))

pdf(paste0(path, "dotplot_antral.pdf"), width = 25, height = 15)
plot_oi
dev.off()

plot_oi
```

```{r dotplot_state3_atretic}
group_oi = "state3_atretic"

prioritized_tbl_oi = prioritized_tbl_oi_network %>% filter(group == group_oi)
plot_oi = make_sample_lr_prod_activity_plots_Omnipath(
  multinichenet_output$prioritization_tables, 
  prioritized_tbl_oi %>% inner_join(lr_network_all))

pdf(paste0(path, "dotplot_atretic.pdf"), width = 25, height = 15)
plot_oi
dev.off()

plot_oi
```